package cards

const (
	FileId_GameInfo  string = "CAACAgQAAxkBAAIInWJHCoZUzBnqRXji8WHMZCqUWNWjAALEAgACX1eZAAGi2Qy93IIQwiME"
	FileId_DrawIcon  string = "CAACAgQAAxkBAAIIk2JHCn7Vgv4UZiqR7xouCoCBQEM3AAL4AgACX1eZAAH-TdXSlvEa2yME"
	FileId_DrawText  string = "CAACAgQAAxkBAAIIlWJHCn_PNjj-lZ_jQTX0C0O_OcYXAALMAgACX1eZAAH8oQKsIYONPCME"
	FileId_PassText  string = "CAACAgQAAxkBAAIImWJHCoIqzvYwzwWvT4X0sdH1ot-LAALOAgACX1eZAAHec7yiXsSGYyME"
	FileId_PassIcon  string = "CAACAgQAAxkBAAIIl2JHCoHz6Ev5y2ftWp9nJGY1JfvdAAL6AgACX1eZAAFuilR5QnD-VyME"
	FileId_CallBluff string = "CAACAgQAAxkBAAIIm2JHCoU_98nnwuJ6Y8e1wEsaZeCwAALKAgACX1eZAAHBw478rNqN0CME"
)
