package cards

// generated by card_gen.py, based on cards/gray_card_constants.go

var GrayCardFileIDs = []string{
	// Green cards
	fileId_Gray_Green_Zero, fileId_Gray_Green_One, fileId_Gray_Green_Two, fileId_Gray_Green_Three, fileId_Gray_Green_Four, fileId_Gray_Green_Five, fileId_Gray_Green_Six, fileId_Gray_Green_Seven, fileId_Gray_Green_Eight, fileId_Gray_Green_Nine, fileId_Gray_Green_PlusTwo, fileId_Gray_Green_Reverse, fileId_Gray_Green_Skip,

	// Red cards
	fileId_Gray_Red_Zero, fileId_Gray_Red_One, fileId_Gray_Red_Two, fileId_Gray_Red_Three, fileId_Gray_Red_Four, fileId_Gray_Red_Five, fileId_Gray_Red_Six, fileId_Gray_Red_Seven, fileId_Gray_Red_Eight, fileId_Gray_Red_Nine, fileId_Gray_Red_PlusTwo, fileId_Gray_Red_Reverse, fileId_Gray_Red_Skip,

	// Yellow cards
	fileId_Gray_Yellow_Zero, fileId_Gray_Yellow_One, fileId_Gray_Yellow_Two, fileId_Gray_Yellow_Three, fileId_Gray_Yellow_Four, fileId_Gray_Yellow_Five, fileId_Gray_Yellow_Six, fileId_Gray_Yellow_Seven, fileId_Gray_Yellow_Eight, fileId_Gray_Yellow_Nine, fileId_Gray_Yellow_PlusTwo, fileId_Gray_Yellow_Reverse, fileId_Gray_Yellow_Skip,

	// Blue cards
	fileId_Gray_Blue_Zero, fileId_Gray_Blue_One, fileId_Gray_Blue_Two, fileId_Gray_Blue_Three, fileId_Gray_Blue_Four, fileId_Gray_Blue_Five, fileId_Gray_Blue_Six, fileId_Gray_Blue_Seven, fileId_Gray_Blue_Eight, fileId_Gray_Blue_Nine, fileId_Gray_Blue_PlusTwo, fileId_Gray_Blue_Reverse, fileId_Gray_Blue_Skip,

	// Black cards
	fileId_Gray_Colorchooser, fileId_Gray_PlusFour,
}

// color -> cards file ids lookup table
var GrayCardFileIDsByColor = map[CardColor][]string{
	Green:  GrayCardFileIDs[0:13],
	Red:    GrayCardFileIDs[13:26],
	Yellow: GrayCardFileIDs[26:39],
	Blue:   GrayCardFileIDs[39:52],
	Wild:   GrayCardFileIDs[52:54],
}
